name: Responder
description: A Command TEster Plugin
main: imwood04\Respond\Main
author: imwood04
version: 1.0.0
api: [3.0.0]

commands:
  respond:
    description: Responds well should...
    usage: "/respond"
    permission: respond.command.respond
permissions:
  respond.command.respond:
    description: "Allows the user to run the command"
    default: true

