name: Responder
description: A Command TEster Plugin
main: Imwood04\Main
author: Imwood04/ZeroTwo#8676
version: 1.0.0
api: [3.0.0]

commands:
  fly:
    description: Allows Flight well should...
    usage: "/fly"
    permission: fly.command.fly
permissions:
  fly.command.fly:
    description: "Allows the user to run the command"
    default: true

